// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnoSurfaces.Infrastructure.Data;

#nullable disable

namespace TechnoSurfaces.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TechnoSurfacesDbContext))]
    [Migration("20261003143924_AddQuotationTermsAndBrands")]
    partial class AddQuotationTermsAndBrands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnoSurfaces.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("EntityName", "EntityKey");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialWarranty")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("WorkmanshipWarranty")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands", t =>
                        {
                            t.HasCheckConstraint("CK_Brand_WarrantyComplete", "([MaterialWarranty] IS NULL AND [WorkmanshipWarranty] IS NULL) OR ([MaterialWarranty] IS NOT NULL AND [WorkmanshipWarranty] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("PriceBandId")
                        .HasColumnType("int");

                    b.Property<int>("ProductLineId")
                        .HasColumnType("int");

                    b.Property<string>("Range")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("PriceBandId");

                    b.HasIndex("Status");

                    b.HasIndex("ProductLineId", "Name")
                        .IsUnique();

                    b.ToTable("Colours");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.MaterialPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CapturedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ColourId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int?>("PriceBandId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerSqm")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SheetSizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SheetSizeId");

                    b.HasIndex("ColourId", "SheetSizeId")
                        .IsUnique()
                        .HasDatabaseName("UX_MaterialPrices_OneOpenPricePerColour")
                        .HasFilter("[ColourId] IS NOT NULL AND [EffectiveTo] IS NULL");

                    b.HasIndex("PriceBandId", "SheetSizeId")
                        .IsUnique()
                        .HasDatabaseName("UX_MaterialPrices_OneOpenPricePerBand")
                        .HasFilter("[PriceBandId] IS NOT NULL AND [EffectiveTo] IS NULL");

                    b.HasIndex("ColourId", "SheetSizeId", "EffectiveFrom");

                    b.HasIndex("PriceBandId", "SheetSizeId", "EffectiveFrom");

                    b.ToTable("MaterialPrices", t =>
                        {
                            t.HasTrigger("TR_MaterialPrices_NoOverlap");

                            t.HasCheckConstraint("CK_MaterialPrice_ColourOrBand", "([ColourId] IS NOT NULL AND [PriceBandId] IS NULL) OR ([ColourId] IS NULL AND [PriceBandId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_MaterialPrice_Period", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_MaterialPrice_Positive", "[PricePerSqm] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.PriceBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ProductLineId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("ProductLineId", "Code")
                        .IsUnique();

                    b.ToTable("PriceBands");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.ProductLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("ThicknessMm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SupplierId", "Name", "ThicknessMm")
                        .IsUnique();

                    b.ToTable("ProductLines");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.RateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Derivation")
                        .HasColumnType("int");

                    b.Property<decimal>("DerivationFactor")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("DerivedFromRateItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DerivedFromRateItemMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBelowTheLine")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DerivedFromRateItemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Category", "SortOrder");

                    b.ToTable("RateItems");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.RatePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<int>("RateItemId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("RateItemId", "SupplierId")
                        .IsUnique()
                        .HasDatabaseName("UX_RatePrices_OneOpenRate")
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.HasIndex("RateItemId", "SupplierId", "EffectiveFrom");

                    b.ToTable("RatePrices", t =>
                        {
                            t.HasTrigger("TR_RatePrices_NoOverlap");

                            t.HasCheckConstraint("CK_RatePrice_NotNegative", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_RatePrice_Period", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.SheetSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LengthMm")
                        .HasColumnType("int");

                    b.Property<int>("ProductLineId")
                        .HasColumnType("int");

                    b.Property<int>("WidthMm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductLineId", "LengthMm", "WidthMm")
                        .IsUnique();

                    b.ToTable("SheetSizes");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdhesivePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeliveryTerms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("PriceListDated")
                        .HasColumnType("date");

                    b.Property<int>("PricingStructure")
                        .HasColumnType("int");

                    b.Property<string>("TradingAs")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.People.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.People.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.People.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.CostingLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Derivation")
                        .HasColumnType("int");

                    b.Property<decimal>("DerivationFactor")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsBelowTheLine")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQuantityOverridden")
                        .HasColumnType("bit");

                    b.Property<int>("LineType")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialPriceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OverriddenUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceOrigin")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuoteVersionId")
                        .HasColumnType("int");

                    b.Property<int?>("RateItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("ResolvedUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SheetAreaM2")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("SupplierDiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialPriceId");

                    b.HasIndex("QuoteVersionId");

                    b.HasIndex("RateItemId");

                    b.ToTable("CostingLines", t =>
                        {
                            t.HasCheckConstraint("CK_CostingLine_MaterialOrRate", "([MaterialPriceId] IS NOT NULL AND [RateItemId] IS NULL) OR ([MaterialPriceId] IS NULL AND [RateItemId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.InvoiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountIncVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("QuoteId")
                        .IsUnique();

                    b.ToTable("InvoiceRecords");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.QuotationLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountExVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuoteVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuoteVersionId");

                    b.ToTable("QuotationLines");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.QuotationTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Section", "SortOrder");

                    b.ToTable("QuotationTerms", t =>
                        {
                            t.HasCheckConstraint("CK_QuotationTerm_TextNotBlank", "[Text] <> ''");
                        });
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Project")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Site")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Status", "IssueDate");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.QuoteVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<decimal>("MarkupPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<decimal>("TransportAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "VersionNo")
                        .IsUnique();

                    b.ToTable("QuoteVersions");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.Colour", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.PriceBand", "PriceBand")
                        .WithMany("Colours")
                        .HasForeignKey("PriceBandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechnoSurfaces.Domain.Catalogue.ProductLine", "ProductLine")
                        .WithMany("Colours")
                        .HasForeignKey("ProductLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PriceBand");

                    b.Navigation("ProductLine");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.MaterialPrice", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechnoSurfaces.Domain.Catalogue.PriceBand", "PriceBand")
                        .WithMany()
                        .HasForeignKey("PriceBandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechnoSurfaces.Domain.Catalogue.SheetSize", "SheetSize")
                        .WithMany()
                        .HasForeignKey("SheetSizeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("PriceBand");

                    b.Navigation("SheetSize");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.PriceBand", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.ProductLine", "ProductLine")
                        .WithMany()
                        .HasForeignKey("ProductLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TechnoSurfaces.Domain.Catalogue.Supplier", "Supplier")
                        .WithMany("PriceBands")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductLine");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.ProductLine", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.Brand", "Brand")
                        .WithMany("ProductLines")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechnoSurfaces.Domain.Catalogue.Supplier", "Supplier")
                        .WithMany("ProductLines")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.RateItem", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.RateItem", "DerivedFromRateItem")
                        .WithMany()
                        .HasForeignKey("DerivedFromRateItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DerivedFromRateItem");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.RatePrice", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.RateItem", "RateItem")
                        .WithMany("Prices")
                        .HasForeignKey("RateItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TechnoSurfaces.Domain.Catalogue.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RateItem");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.SheetSize", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.ProductLine", "ProductLine")
                        .WithMany("SheetSizes")
                        .HasForeignKey("ProductLineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductLine");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.People.Contact", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.People.Customer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.CostingLine", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Catalogue.MaterialPrice", null)
                        .WithMany()
                        .HasForeignKey("MaterialPriceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechnoSurfaces.Domain.Quoting.QuoteVersion", null)
                        .WithMany("CostingLines")
                        .HasForeignKey("QuoteVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TechnoSurfaces.Domain.Catalogue.RateItem", null)
                        .WithMany()
                        .HasForeignKey("RateItemId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.InvoiceRecord", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Quoting.Quote", "Quote")
                        .WithOne()
                        .HasForeignKey("TechnoSurfaces.Domain.Quoting.InvoiceRecord", "QuoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.QuotationLine", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Quoting.QuoteVersion", null)
                        .WithMany("QuotationLines")
                        .HasForeignKey("QuoteVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.Quote", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.People.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TechnoSurfaces.Domain.People.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.QuoteVersion", b =>
                {
                    b.HasOne("TechnoSurfaces.Domain.Quoting.Quote", "Quote")
                        .WithMany("Versions")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.Brand", b =>
                {
                    b.Navigation("ProductLines");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.PriceBand", b =>
                {
                    b.Navigation("Colours");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.ProductLine", b =>
                {
                    b.Navigation("Colours");

                    b.Navigation("SheetSizes");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.RateItem", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Catalogue.Supplier", b =>
                {
                    b.Navigation("PriceBands");

                    b.Navigation("ProductLines");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.People.Customer", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.Quote", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TechnoSurfaces.Domain.Quoting.QuoteVersion", b =>
                {
                    b.Navigation("CostingLines");

                    b.Navigation("QuotationLines");
                });
#pragma warning restore 612, 618
        }
    }
}
